[package]
name = "kzg"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
common = {path = "../common"}

ark-bn254 = "0.5.0"
ark-ec = "0.5.0"
ark-ff = "0.5.0"
ark-poly = "0.5.0"
ark-std = "0.5.0"
rand = "0.8.5"

